version: '2.1'
services:
  ekar-mysql:
    container_name: drones-mysql
    image: 'mysql/mysql-server:8.0.31-1.2.10-server'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drones_db
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
  ekar-app:
    image: drones-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8087:8080'
    volumes:
      - /data/drones-app
    depends_on:
      ekar-mysql:
        condition: service_healthy

